CLASS ZCL_TEST_AY DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES IF_OO_ADT_CLASSRUN.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_TEST_AY IMPLEMENTATION.


  METHOD IF_OO_ADT_CLASSRUN~MAIN.
    OUT->WRITE('Hello World').
  ENDMETHOD.
ENDCLASS.
